name: First GitHub Action

on: 
  push:   # jab bhi code push hoga ye chalega
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # repo ka code le aata hai

      - name: Run Hello World
        run: echo "Hello, GitHub Actions!"
